<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;

class ProjectSeeder extends Seeder
{
    /**
     * Seed the application's projects with content from the portfolio.
     */
    public function run(): void
    {
        $projects = [
            // ── Personal projects ────────────────────────────────────────────
            [
                'title' => 'Triz AI',
                'slug' => 'triz-ai',
                'category' => 'personal',
                'type' => 'documentation',
                'summary' => 'The Trizai System Architecture info site — a comprehensive showcase of the God of the Tech Field harness including all 19 roles, 94 skills, 21 workflows, memory systems, and engineering discipline.',
                'description' => 'A documentation and architecture showcase site for the Trizai development system. It presents the complete engineering harness — 19 expert roles, 94 reusable skills, 21 execution workflows, the memory system, and the engineering discipline that binds it together. Built as a single-page documentation hub with a focus on readability and structure.',
                'role' => 'Solo Developer',
                'year' => '2026',
                'featured' => true,
                'technologies' => ['HTML', 'CSS', 'JavaScript', 'Cloudflare Pages'],
                'url' => 'https://trizai-html.pages.dev',
                'source_url' => null,
                'sort_order' => 1,
            ],
            [
                'title' => 'ItemVision AI',
                'slug' => 'itemvision-ai',
                'category' => 'personal',
                'type' => 'ai-tools',
                'summary' => 'A real-time object and face tracking web application that uses your camera to detect and track items, faces, and objects through AI-powered computer vision.',
                'description' => 'A browser-based computer vision tool that taps into the device camera to detect and track objects, faces, and items in real time. Demonstrates practical use of the Camera API and AI-powered detection without needing a dedicated app install.',
                'role' => 'Solo Developer',
                'year' => '2026',
                'featured' => false,
                'technologies' => ['JavaScript', 'AI', 'Camera API', 'Cloudflare Pages'],
                'url' => 'https://item-vision.pages.dev',
                'source_url' => null,
                'sort_order' => 2,
            ],
            [
                'title' => 'Wordle',
                'slug' => 'wordle',
                'category' => 'personal',
                'type' => 'game',
                'summary' => 'A Wordle clone game — an exact NYT Wordle design clone where players guess 5-letter words with color feedback on each attempt.',
                'description' => 'A faithful recreation of the classic NYT Wordle experience. Players guess 5-letter words with real-time color feedback — green for correct position, yellow for present, gray for absent — backed by a word bank and streak tracking.',
                'role' => 'Solo Developer',
                'year' => '2026',
                'featured' => false,
                'technologies' => ['JavaScript', 'HTML/CSS', 'Game', 'Wordle Clone', 'Cloudflare Pages'],
                'url' => 'https://wordle-game-bxo.pages.dev',
                'source_url' => null,
                'sort_order' => 3,
            ],
            [
                'title' => 'Type monk E',
                'slug' => 'type-monk-e',
                'category' => 'personal',
                'type' => 'game',
                'summary' => 'A typing test website designed to help users improve their typing speed and accuracy with a clean, minimal interface and real-time WPM tracking.',
                'description' => 'A minimal typing practice tool with real-time words-per-minute and accuracy tracking. Clean interface, randomized passages, and immediate feedback on every session.',
                'role' => 'Solo Developer',
                'year' => '2026',
                'featured' => false,
                'technologies' => ['JavaScript', 'HTML/CSS', 'Typing Test', 'Cloudflare Pages'],
                'url' => 'https://type-monk-e.pages.dev',
                'source_url' => null,
                'sort_order' => 4,
            ],

            // ── Academic projects ────────────────────────────────────────────
            [
                'title' => 'ISakay',
                'slug' => 'isakay',
                'category' => 'academic',
                'type' => 'web-app',
                'summary' => 'A client-server transportation ticketing web app that enables users to book rides with jeepney drivers by selecting travel schedules and reserving specific seats.',
                'description' => 'A full-stack transportation ticketing system built for the local jeepney commuting experience. Passengers select travel schedules, view seat availability, and reserve seats; drivers manage their routes and manifests. Delivered as a capstone-scale client-server application.',
                'role' => 'Project Leader, Lead Programmer, Full-Stack Developer',
                'year' => '2024',
                'featured' => true,
                'technologies' => ['PHP', 'JavaScript', 'MySQL', 'Bootstrap'],
                'url' => null,
                'source_url' => null,
                'sort_order' => 5,
            ],
            [
                'title' => 'Cryptopredictor',
                'slug' => 'cryptopredictor',
                'category' => 'academic',
                'type' => 'ml-data',
                'summary' => 'Advanced forecasting software using machine learning to predict cryptocurrency price movements by analyzing historical data, market trends, and trading volumes.',
                'description' => 'A machine learning forecasting application that ingests historical crypto market data — prices, trends, and trading volumes — to model and predict potential price movements. Python-based with a Flask frontend and SQL data layer.',
                'role' => 'Project Leader, Lead Programmer, Full-Stack Developer',
                'year' => '2024',
                'featured' => false,
                'technologies' => ['Python', 'Machine Learning', 'Flask', 'SQL'],
                'url' => null,
                'source_url' => null,
                'sort_order' => 6,
            ],
            [
                'title' => 'ARventure',
                'slug' => 'arventure',
                'category' => 'academic',
                'type' => 'ar-mobile',
                'summary' => 'An Augmented Reality Indoor Navigation Application that helps users navigate through buildings using AR technology, even in an offline setup.',
                'description' => 'An augmented reality indoor navigation app built with Unity. Users navigate buildings via AR overlays with no internet dependency — a fully offline indoor wayfinding experience using AR Foundation and Vuforia.',
                'role' => 'Lead Programmer, Full-Stack Developer',
                'year' => '2024',
                'featured' => false,
                'technologies' => ['Unity', 'C#', 'AR Foundation', 'Vuforia'],
                'url' => null,
                'source_url' => null,
                'sort_order' => 7,
            ],
            [
                'title' => 'Aldrin Stream',
                'slug' => 'aldrin-stream',
                'category' => 'academic',
                'type' => 'web-app',
                'summary' => 'A web application where users can watch videos in real time — either pre-uploaded videos played sequentially or live video streams — with a fully responsive design.',
                'description' => 'A client-server video platform supporting both sequential playback of pre-uploaded videos and live streaming, delivered with a fully responsive interface.',
                'role' => 'Project Leader, Lead Programmer, Full-Stack Developer',
                'year' => '2023',
                'featured' => false,
                'technologies' => ['PHP', 'JavaScript', 'MySQL', 'HTML/CSS'],
                'url' => null,
                'source_url' => null,
                'sort_order' => 8,
            ],
            [
                'title' => 'Kronos',
                'slug' => 'kronos',
                'category' => 'academic',
                'type' => 'web-app',
                'summary' => 'A time tracking system for employees to log time in/out, enabling employers to accurately monitor and record working hours for attendance management.',
                'description' => 'An employee time-tracking and attendance system. Employees log time in/out; employers monitor working hours and manage attendance records with reporting.',
                'role' => 'Back-End Developer',
                'year' => '2023',
                'featured' => false,
                'technologies' => ['PHP', 'MySQL', 'JavaScript'],
                'url' => null,
                'source_url' => null,
                'sort_order' => 9,
            ],
            [
                'title' => 'Wordy',
                'slug' => 'wordy',
                'category' => 'academic',
                'type' => 'game',
                'summary' => 'A competitive word game where players compete to form the longest possible word from a given set of letters.',
                'description' => 'A competitive multiplayer word game — players race to build the longest valid word from a shared letter pool, with scoring and rounds.',
                'role' => 'Full-Stack Developer',
                'year' => '2023',
                'featured' => false,
                'technologies' => ['PHP', 'JavaScript', 'MySQL', 'HTML/CSS'],
                'url' => null,
                'source_url' => null,
                'sort_order' => 10,
            ],
            [
                'title' => 'Chatting System (LAN)',
                'slug' => 'chatting-system-lan',
                'category' => 'academic',
                'type' => 'networking',
                'summary' => 'A client-server application enabling real-time communication over a Local Area Network for seamless message exchange within the network.',
                'description' => 'A LAN-based messaging system demonstrating client-server architecture — real-time message exchange between connected clients over a local network.',
                'role' => 'Full-Stack Developer',
                'year' => '2023',
                'featured' => false,
                'technologies' => ['PHP', 'JavaScript', 'MySQL', 'Networking'],
                'url' => null,
                'source_url' => null,
                'sort_order' => 11,
            ],
        ];

        foreach ($projects as $project) {
            Project::updateOrCreate(['slug' => $project['slug']], $project);
        }
    }
}
